from collections.abc import Sequence
from typing import Final, final

from _typeshed import Incomplete

from sm4sh_model_py.vertex import Vertices

# TODO: Is there a way for pyo3 to generate these imports?
from . import animation, database, model, skinning, texture, vertex

@final
class AlphaFunc:
    Always: Final[AlphaFunc]
    Disabled: Final[AlphaFunc]
    Equal: Final[AlphaFunc]
    Greater: Final[AlphaFunc]
    GreaterEqual: Final[AlphaFunc]
    Less: Final[AlphaFunc]
    Never: Final[AlphaFunc]
    NotEqual: Final[AlphaFunc]
    def __eq__(self, /, other: object) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class BoneFlags:
    Disabled: Final[BoneFlags]
    ParentBone: Final[BoneFlags]
    Skinning: Final[BoneFlags]
    def __eq__(self, /, other: object) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class BoneType:
    Follow: Final[BoneType]
    Helper: Final[BoneType]
    Normal: Final[BoneType]
    Swing: Final[BoneType]
    def __eq__(self, /, other: object) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class CullMode:
    Disabled: Final[CullMode]
    Disabled2: Final[CullMode]
    Inside: Final[CullMode]
    Inside2: Final[CullMode]
    Outside: Final[CullMode]
    Outside2: Final[CullMode]
    def __eq__(self, /, other: object) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class DstFactor:
    One: Final[DstFactor]
    One2: Final[DstFactor]
    One3: Final[DstFactor]
    One4: Final[DstFactor]
    One5: Final[DstFactor]
    OneMinusDestinationAlpha: Final[DstFactor]
    OneMinusSourceAlpha: Final[DstFactor]
    OneMinusSourceAlpha2: Final[DstFactor]
    OneMinusSourceAlpha3: Final[DstFactor]
    OneReverseSubtract: Final[DstFactor]
    SourceAlpha: Final[DstFactor]
    SourceAlphaReverseSubtract: Final[DstFactor]
    Unk10: Final[DstFactor]
    Zero: Final[DstFactor]
    Zero2: Final[DstFactor]
    Zero3: Final[DstFactor]
    Zero5: Final[DstFactor]
    def __eq__(self, /, other: object) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class EncodeSurfaceRgba32FloatArgs:
    def __new__(
        cls,
        /,
        hash_id: int,
        width: int,
        height: int,
        layers: int,
        image_format: NutFormat,
        mipmaps: bool,
        data: Incomplete,
    ) -> EncodeSurfaceRgba32FloatArgs: ...
    @property
    def data(self, /) -> Incomplete: ...
    @data.setter
    def data(self, /, value: Incomplete) -> None: ...
    def encode(self, /) -> ImageTexture: ...
    @property
    def hash_id(self, /) -> int: ...
    @hash_id.setter
    def hash_id(self, /, value: int) -> None: ...
    @property
    def height(self, /) -> int: ...
    @height.setter
    def height(self, /, value: int) -> None: ...
    @property
    def image_format(self, /) -> NutFormat: ...
    @image_format.setter
    def image_format(self, /, value: NutFormat) -> None: ...
    @property
    def layers(self, /) -> int: ...
    @layers.setter
    def layers(self, /, value: int) -> None: ...
    @property
    def mipmaps(self, /) -> bool: ...
    @mipmaps.setter
    def mipmaps(self, /, value: bool) -> None: ...
    @property
    def width(self, /) -> int: ...
    @width.setter
    def width(self, /, value: int) -> None: ...

@final
class ImageTexture:
    def __new__(
        cls,
        /,
        hash_id: int,
        width: int,
        height: int,
        mipmap_count: int,
        layers: int,
        image_format: NutFormat,
        image_data: Sequence[int],
    ) -> ImageTexture: ...
    @property
    def hash_id(self, /) -> int: ...
    @hash_id.setter
    def hash_id(self, /, value: int) -> None: ...
    @property
    def height(self, /) -> int: ...
    @height.setter
    def height(self, /, value: int) -> None: ...
    @property
    def image_data(self, /) -> bytes: ...
    @image_data.setter
    def image_data(self, /, value: Sequence[int]) -> None: ...
    @property
    def image_format(self, /) -> NutFormat: ...
    @image_format.setter
    def image_format(self, /, value: NutFormat) -> None: ...
    @property
    def layers(self, /) -> int: ...
    @layers.setter
    def layers(self, /, value: int) -> None: ...
    @property
    def mipmap_count(self, /) -> int: ...
    @mipmap_count.setter
    def mipmap_count(self, /, value: int) -> None: ...
    @property
    def width(self, /) -> int: ...
    @width.setter
    def width(self, /, value: int) -> None: ...

@final
class MagFilter:
    Linear: Final[MagFilter]
    Nearest: Final[MagFilter]
    Unk0: Final[MagFilter]
    def __eq__(self, /, other: object) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class MapMode:
    EnvCamera: Final[MapMode]
    EnvLight: Final[MapMode]
    EnvSpec: Final[MapMode]
    Projection: Final[MapMode]
    TexCoord: Final[MapMode]
    def __eq__(self, /, other: object) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class MinFilter:
    Linear: Final[MinFilter]
    LinearMipmapLinear: Final[MinFilter]
    Nearest: Final[MinFilter]
    NearestMipmapLinear: Final[MinFilter]
    def __eq__(self, /, other: object) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class MipDetail:
    FourMipLevels: Final[MipDetail]
    FourMipLevelsAnisotropic: Final[MipDetail]
    FourMipLevelsTrilinear: Final[MipDetail]
    FourMipLevelsTrilinearAnisotropic: Final[MipDetail]
    OneMipLevelAnisotropicOff: Final[MipDetail]
    OneMipLevelAnisotropicOff2: Final[MipDetail]
    Unk1: Final[MipDetail]
    def __eq__(self, /, other: object) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class Nud:
    def save(self, /, path: str) -> None: ...

@final
class NudMaterial:
    def __deepcopy__(self, /, _memo: dict) -> NudMaterial: ...
    def __new__(
        cls,
        /,
        shader_id: int,
        src_factor: SrcFactor,
        dst_factor: DstFactor,
        alpha_func: AlphaFunc,
        alpha_test_ref: int,
        cull_mode: CullMode,
        textures: list[NudTexture],
        properties: list[NudProperty],
    ) -> NudMaterial: ...
    @property
    def alpha_func(self, /) -> AlphaFunc: ...
    @alpha_func.setter
    def alpha_func(self, /, value: AlphaFunc) -> None: ...
    @property
    def alpha_test_ref(self, /) -> int: ...
    @alpha_test_ref.setter
    def alpha_test_ref(self, /, value: int) -> None: ...
    @property
    def cull_mode(self, /) -> CullMode: ...
    @cull_mode.setter
    def cull_mode(self, /, value: CullMode) -> None: ...
    @property
    def dst_factor(self, /) -> DstFactor: ...
    @dst_factor.setter
    def dst_factor(self, /, value: DstFactor) -> None: ...
    @property
    def properties(self, /) -> list[NudProperty]: ...
    @properties.setter
    def properties(self, /, value: list[NudProperty]) -> None: ...
    @property
    def shader_id(self, /) -> int: ...
    @shader_id.setter
    def shader_id(self, /, value: int) -> None: ...
    @property
    def src_factor(self, /) -> SrcFactor: ...
    @src_factor.setter
    def src_factor(self, /, value: SrcFactor) -> None: ...
    @property
    def textures(self, /) -> list[NudTexture]: ...
    @textures.setter
    def textures(self, /, value: list[NudTexture]) -> None: ...

@final
class NudMesh:
    def __deepcopy__(self, /, _memo: dict) -> NudMesh: ...
    def __new__(
        cls,
        /,
        vertices: Vertices,
        vertex_indices: Incomplete,
        primitive_type: PrimitiveType,
        material1: NudMaterial | None,
        material2: NudMaterial | None,
        material3: NudMaterial | None,
        material4: NudMaterial | None,
    ) -> NudMesh: ...
    @property
    def material1(self, /) -> NudMaterial | None: ...
    @material1.setter
    def material1(self, /, value: NudMaterial | None) -> None: ...
    @property
    def material2(self, /) -> NudMaterial | None: ...
    @material2.setter
    def material2(self, /, value: NudMaterial | None) -> None: ...
    @property
    def material3(self, /) -> NudMaterial | None: ...
    @material3.setter
    def material3(self, /, value: NudMaterial | None) -> None: ...
    @property
    def material4(self, /) -> NudMaterial | None: ...
    @material4.setter
    def material4(self, /, value: NudMaterial | None) -> None: ...
    @property
    def primitive_type(self, /) -> PrimitiveType: ...
    @primitive_type.setter
    def primitive_type(self, /, value: PrimitiveType) -> None: ...
    def triangle_list_indices(self, /) -> Incomplete: ...
    @property
    def vertex_indices(self, /) -> Incomplete: ...
    @vertex_indices.setter
    def vertex_indices(self, /, value: Incomplete) -> None: ...
    @property
    def vertices(self, /) -> Vertices: ...
    @vertices.setter
    def vertices(self, /, value: Vertices) -> None: ...

@final
class NudMeshGroup:
    def __deepcopy__(self, /, _memo: dict) -> NudMeshGroup: ...
    def __new__(
        cls,
        /,
        name: str,
        meshes: list[NudMesh],
        sort_bias: float,
        bounding_sphere: Sequence[float],
        parent_bone_index: int | None,
    ) -> NudMeshGroup: ...
    @property
    def bounding_sphere(self, /) -> list[float]: ...
    @bounding_sphere.setter
    def bounding_sphere(self, /, value: Sequence[float]) -> None: ...
    @property
    def meshes(self, /) -> list[NudMesh]: ...
    @meshes.setter
    def meshes(self, /, value: list[NudMesh]) -> None: ...
    @property
    def name(self, /) -> str: ...
    @name.setter
    def name(self, /, value: str) -> None: ...
    @property
    def parent_bone_index(self, /) -> int | None: ...
    @parent_bone_index.setter
    def parent_bone_index(self, /, value: int | None) -> None: ...
    @property
    def sort_bias(self, /) -> float: ...
    @sort_bias.setter
    def sort_bias(self, /, value: float) -> None: ...

@final
class NudModel:
    def __deepcopy__(self, /, _memo: dict) -> NudModel: ...
    def __new__(
        cls,
        /,
        groups: list[NudMeshGroup],
        textures: list[ImageTexture],
        bounding_sphere: Sequence[float],
        skeleton: VbnSkeleton | None,
    ) -> NudModel: ...
    @property
    def bounding_sphere(self, /) -> list[float]: ...
    @bounding_sphere.setter
    def bounding_sphere(self, /, value: Sequence[float]) -> None: ...
    @property
    def groups(self, /) -> list[NudMeshGroup]: ...
    @groups.setter
    def groups(self, /, value: list[NudMeshGroup]) -> None: ...
    @property
    def skeleton(self, /) -> VbnSkeleton | None: ...
    @skeleton.setter
    def skeleton(self, /, value: VbnSkeleton | None) -> None: ...
    @property
    def textures(self, /) -> list[ImageTexture]: ...
    @textures.setter
    def textures(self, /, value: list[ImageTexture]) -> None: ...
    def to_nud(self, /) -> Nud: ...
    def to_nut(self, /) -> Nut: ...

@final
class NudProperty:
    def __new__(cls, /, name: str, values: Sequence[float]) -> NudProperty: ...
    @property
    def name(self, /) -> str: ...
    @name.setter
    def name(self, /, value: str) -> None: ...
    @property
    def values(self, /) -> list[float]: ...
    @values.setter
    def values(self, /, value: Sequence[float]) -> None: ...

@final
class NudTexture:
    def __new__(
        cls,
        /,
        hash: int,
        map_mode: MapMode,
        wrap_mode_s: WrapMode,
        wrap_mode_t: WrapMode,
        min_filter: MinFilter,
        mag_filter: MagFilter,
        mip_detail: MipDetail,
    ) -> NudTexture: ...
    @property
    def hash(self, /) -> int: ...
    @hash.setter
    def hash(self, /, value: int) -> None: ...
    @property
    def mag_filter(self, /) -> MagFilter: ...
    @mag_filter.setter
    def mag_filter(self, /, value: MagFilter) -> None: ...
    @property
    def map_mode(self, /) -> MapMode: ...
    @map_mode.setter
    def map_mode(self, /, value: MapMode) -> None: ...
    @property
    def min_filter(self, /) -> MinFilter: ...
    @min_filter.setter
    def min_filter(self, /, value: MinFilter) -> None: ...
    @property
    def mip_detail(self, /) -> MipDetail: ...
    @mip_detail.setter
    def mip_detail(self, /, value: MipDetail) -> None: ...
    @property
    def wrap_mode_s(self, /) -> WrapMode: ...
    @wrap_mode_s.setter
    def wrap_mode_s(self, /, value: WrapMode) -> None: ...
    @property
    def wrap_mode_t(self, /) -> WrapMode: ...
    @wrap_mode_t.setter
    def wrap_mode_t(self, /, value: WrapMode) -> None: ...

@final
class Nut:
    def save(self, /, path: str) -> None: ...

@final
class NutFormat:
    B5G6R5Unorm: Final[NutFormat]
    BC1Unorm: Final[NutFormat]
    BC2Unorm: Final[NutFormat]
    BC3Unorm: Final[NutFormat]
    BC5Unorm: Final[NutFormat]
    Bgr5A1Unorm: Final[NutFormat]
    Bgr5A1Unorm2: Final[NutFormat]
    R32Float: Final[NutFormat]
    Rgb5A1Unorm: Final[NutFormat]
    Rgba82: Final[NutFormat]
    Rgba8Unorm: Final[NutFormat]
    def __eq__(self, /, other: object) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class PrimitiveType:
    TriangleList: Final[PrimitiveType]
    TriangleStrip: Final[PrimitiveType]
    def __eq__(self, /, other: object) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class SrcFactor:
    DestinationAlpha: Final[SrcFactor]
    DestinationAlpha7: Final[SrcFactor]
    DestinationColor: Final[SrcFactor]
    One: Final[SrcFactor]
    One2: Final[SrcFactor]
    SourceAlpha: Final[SrcFactor]
    SourceAlpha2: Final[SrcFactor]
    SourceAlpha3: Final[SrcFactor]
    SrcAlpha3: Final[SrcFactor]
    SrcAlpha4: Final[SrcFactor]
    SrcAlpha5: Final[SrcFactor]
    Unk16: Final[SrcFactor]
    Unk33: Final[SrcFactor]
    Zero: Final[SrcFactor]
    def __eq__(self, /, other: object) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class VbnBone:
    def __new__(
        cls,
        /,
        name: str,
        hash: int,
        parent_bone_index: int | None,
        bone_type: BoneType,
        translation: Sequence[float],
        rotation: Sequence[float],
        scale: Sequence[float],
    ) -> VbnBone: ...
    @property
    def bone_type(self, /) -> BoneType: ...
    @bone_type.setter
    def bone_type(self, /, value: BoneType) -> None: ...
    @property
    def hash(self, /) -> int: ...
    @hash.setter
    def hash(self, /, value: int) -> None: ...
    @property
    def name(self, /) -> str: ...
    @name.setter
    def name(self, /, value: str) -> None: ...
    @property
    def parent_bone_index(self, /) -> int | None: ...
    @parent_bone_index.setter
    def parent_bone_index(self, /, value: int | None) -> None: ...
    @property
    def rotation(self, /) -> list[float]: ...
    @rotation.setter
    def rotation(self, /, value: Sequence[float]) -> None: ...
    @property
    def scale(self, /) -> list[float]: ...
    @scale.setter
    def scale(self, /, value: Sequence[float]) -> None: ...
    @property
    def translation(self, /) -> list[float]: ...
    @translation.setter
    def translation(self, /, value: Sequence[float]) -> None: ...

@final
class VbnSkeleton:
    def __new__(cls, /, bones: list[VbnBone]) -> VbnSkeleton: ...
    @property
    def bones(self, /) -> list[VbnBone]: ...
    @bones.setter
    def bones(self, /, value: list[VbnBone]) -> None: ...
    def model_space_transforms(self, /) -> Incomplete: ...

@final
class WrapMode:
    ClampToEdge: Final[WrapMode]
    MirroredRepeat: Final[WrapMode]
    Repeat: Final[WrapMode]
    def __eq__(self, /, other: object) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

def decode_images_png(image_textures: Sequence[ImageTexture]) -> list[bytes]: ...
def encode_images_rgbaf32(
    images: Sequence[EncodeSurfaceRgba32FloatArgs],
) -> list[ImageTexture]: ...
def load_model(path: str) -> NudModel: ...
