from typing import final

from _typeshed import Incomplete

from sm4sh_model_py import VbnSkeleton

@final
class Animation:
    def __new__(cls, /, nodes: list[AnimationNode], frame_count: int) -> Animation: ...
    def fcurves(
        self, /, skeleton: VbnSkeleton, use_blender_coordinates: bool
    ) -> FCurves: ...
    @property
    def frame_count(self, /) -> int: ...
    @frame_count.setter
    def frame_count(self, /, value: int) -> None: ...
    def local_space_transforms(
        self, /, skeleton: VbnSkeleton, frame: float
    ) -> Incomplete: ...
    def model_space_transforms(
        self, /, skeleton: VbnSkeleton, frame: float
    ) -> Incomplete: ...
    @property
    def nodes(self, /) -> list[AnimationNode]: ...
    @nodes.setter
    def nodes(self, /, value: list[AnimationNode]) -> None: ...
    def skinning_transforms(
        self, /, skeleton: VbnSkeleton, frame: float
    ) -> Incomplete: ...

@final
class AnimationNode: ...

@final
class FCurves:
    @property
    def rotation(self, /) -> dict: ...
    @rotation.setter
    def rotation(self, /, value: dict) -> None: ...
    @property
    def scale(self, /) -> dict: ...
    @scale.setter
    def scale(self, /, value: dict) -> None: ...
    @property
    def translation(self, /) -> dict: ...
    @translation.setter
    def translation(self, /, value: dict) -> None: ...

def load_animations(path: str) -> list[tuple[str, Animation]]: ...
