from typing import final

from sm4sh_model_py import NudMesh, NudMeshGroup

@final
class NudMeshGroupMesh:
    def __deepcopy__(self, /, _memo: dict) -> NudMeshGroupMesh: ...
    def __new__(
        cls,
        /,
        name: str,
        sort_bias: float,
        parent_bone_index: int | None,
        mesh: NudMesh,
    ) -> NudMeshGroupMesh: ...
    @property
    def mesh(self, /) -> NudMesh: ...
    @mesh.setter
    def mesh(self, /, value: NudMesh) -> None: ...
    @property
    def name(self, /) -> str: ...
    @name.setter
    def name(self, /, value: str) -> None: ...
    @property
    def parent_bone_index(self, /) -> int | None: ...
    @parent_bone_index.setter
    def parent_bone_index(self, /, value: int | None) -> None: ...
    @property
    def sort_bias(self, /) -> float: ...
    @sort_bias.setter
    def sort_bias(self, /, value: float) -> None: ...

def create_mesh_groups(meshes: list[NudMeshGroupMesh]) -> list[NudMeshGroup]: ...
