from typing import final

from _typeshed import Incomplete

from sm4sh_model_py.vertex import BoneElementType

@final
class Influence:
    def __new__(cls, /, bone_name: str, weights: list[VertexWeight]) -> Influence: ...
    @property
    def bone_name(self, /) -> str: ...
    @bone_name.setter
    def bone_name(self, /, value: str) -> None: ...
    @property
    def weights(self, /) -> list[VertexWeight]: ...
    @weights.setter
    def weights(self, /, value: list[VertexWeight]) -> None: ...

@final
class SkinWeights:
    def __new__(
        cls, /, bone_indices: Incomplete, bone_weights: Incomplete
    ) -> SkinWeights: ...
    @property
    def bone_indices(self, /) -> Incomplete: ...
    @bone_indices.setter
    def bone_indices(self, /, value: Incomplete) -> None: ...
    @property
    def bone_weights(self, /) -> Incomplete: ...
    @bone_weights.setter
    def bone_weights(self, /, value: Incomplete) -> None: ...
    @staticmethod
    def from_influences(
        influences: list[Influence],
        vertex_count: int,
        bone_names: list[str],
        element_type: BoneElementType,
    ) -> SkinWeights: ...
    def to_influences(self, /, bone_names: list[str]) -> list[Influence]: ...

@final
class VertexWeight:
    def __new__(cls, /, vertex_index: int, weight: float) -> VertexWeight: ...
    @property
    def vertex_index(self, /) -> int: ...
    @vertex_index.setter
    def vertex_index(self, /, value: int) -> None: ...
    @property
    def weight(self, /) -> float: ...
    @weight.setter
    def weight(self, /, value: float) -> None: ...
