from typing import Final, final

from _typeshed import Incomplete

@final
class BoneElementType:
    Byte: Final[BoneElementType]
    Float16: Final[BoneElementType]
    Float32: Final[BoneElementType]
    def __eq__(self, /, other: object) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class Bones:
    def __new__(
        cls,
        /,
        bone_indices: Incomplete,
        weights: Incomplete,
        element_type: BoneElementType,
    ) -> Bones: ...
    @property
    def bone_indices(self, /) -> Incomplete: ...
    @bone_indices.setter
    def bone_indices(self, /, value: Incomplete) -> None: ...
    @property
    def element_type(self, /) -> BoneElementType: ...
    @element_type.setter
    def element_type(self, /, value: BoneElementType) -> None: ...
    @property
    def weights(self, /) -> Incomplete: ...
    @weights.setter
    def weights(self, /, value: Incomplete) -> None: ...

@final
class ColorElementType:
    Byte: Final[ColorElementType]
    Float16: Final[ColorElementType]
    def __eq__(self, /, other: object) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class Colors:
    def __new__(
        cls, /, colors: Incomplete, element_type: ColorElementType
    ) -> Colors: ...
    @property
    def colors(self, /) -> Incomplete: ...
    @colors.setter
    def colors(self, /, value: Incomplete) -> None: ...
    @property
    def element_type(self, /) -> ColorElementType: ...
    @element_type.setter
    def element_type(self, /, value: ColorElementType) -> None: ...

@final
class Normals:
    @staticmethod
    def from_normals_tangents_bitangents_float16(
        normals: Incomplete, tangents: Incomplete, bitangents: Incomplete
    ) -> Normals: ...
    @staticmethod
    def from_normals_tangents_bitangents_float32(
        normals: Incomplete, tangents: Incomplete, bitangents: Incomplete
    ) -> Normals: ...
    def normals(self, /) -> Incomplete | None: ...

@final
class Uvs:
    @staticmethod
    def from_uvs_float16(uvs: list[Incomplete]) -> Uvs: ...
    @staticmethod
    def from_uvs_float32(uvs: list[Incomplete]) -> Uvs: ...
    def uvs(self, /) -> list[Incomplete]: ...

@final
class Vertices:
    def __new__(
        cls,
        /,
        positions: Incomplete,
        normals: Normals,
        bones: Bones | None,
        colors: Colors | None,
        uvs: Uvs,
    ) -> Vertices: ...
    @property
    def bones(self, /) -> Bones | None: ...
    @bones.setter
    def bones(self, /, value: Bones | None) -> None: ...
    @property
    def colors(self, /) -> Colors | None: ...
    @colors.setter
    def colors(self, /, value: Colors | None) -> None: ...
    @property
    def normals(self, /) -> Normals: ...
    @normals.setter
    def normals(self, /, value: Normals) -> None: ...
    @property
    def positions(self, /) -> Incomplete: ...
    @positions.setter
    def positions(self, /, value: Incomplete) -> None: ...
    @property
    def uvs(self, /) -> Uvs: ...
    @uvs.setter
    def uvs(self, /, value: Uvs) -> None: ...
